# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Docker

on:
  workflow_call:

jobs:
  
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.10.0

    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      uses: docker/login-action@v3.4.0
      with:
        # Username used to log against the Docker registry
        username: dennysdocker2022
        # Password or personal access token used to log against the Docker registry
        password: 
